export const FETCH_BLOG_LIST_REQUEST = "FETCH_BLOG_LIST_REQUEST";
export const FETCH_BLOG_LIST_SUCCESS = "FETCH_BLOG_LIST_SUCCESS";
export const FETCH_BLOG_LIST_FAILURE = "FETCH_BLOG_LIST_FAILURE";

export const FETCH_ADD_BLOG_REQUEST = "FETCH_ADD_BLOG_REQUEST";
export const FETCH_ADD_BLOG_SUCCESS = "FETCH_ADD_BLOG_SUCCESS";
export const FETCH_ADD_BLOG_FAILURE = "FETCH_ADD_BLOG_FAILURE";

export const FETCH_CATEGORY_LIST_REQUEST = "FETCH_CATEGORY_LIST_REQUEST";
export const FETCH_CATEGORY_LIST_SUCCESS = "FETCH_CATEGORY_LIST_SUCCESS";
export const FETCH_CATEGORY_LIST_FAILURE = "FETCH_CATEGORY_LIST_FAILURE";